# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permute_gibbs_beta_normal_cpp <- function(Y, Xbeta, X, sigma, beta, betaind) {
    .Call(`_NPBayes_permute_gibbs_beta_normal_cpp`, Y, Xbeta, X, sigma, beta, betaind)
}

permute_gibbs_beta_logistic_cpp <- function(Y, Xbeta, X, beta) {
    .Call(`_NPBayes_permute_gibbs_beta_logistic_cpp`, Y, Xbeta, X, beta)
}

sample_j_cumulative <- function(cumP, i) {
    .Call(`_NPBayes_sample_j_cumulative`, cumP, i)
}

permute_gibbs_beta_normal_corr_cpp <- function(Y, Xbeta, X, sigma, beta, betaind, cumP) {
    .Call(`_NPBayes_permute_gibbs_beta_normal_corr_cpp`, Y, Xbeta, X, sigma, beta, betaind, cumP)
}

sample_gibbs_beta_logistic_cpp <- function(Y, Xbeta, X, beta, betaind, avec, pivec, innersample = 5L, interval_sample = 2.) {
    .Call(`_NPBayes_sample_gibbs_beta_logistic_cpp`, Y, Xbeta, X, beta, betaind, avec, pivec, innersample, interval_sample)
}

sample_gibbs_beta_normal_cpp <- function(Y, Xbeta, X, sigma, X2diag, beta, betaind, avec, pivec, innersample = 5L, interval_sample = 2.) {
    .Call(`_NPBayes_sample_gibbs_beta_normal_cpp`, Y, Xbeta, X, sigma, X2diag, beta, betaind, avec, pivec, innersample, interval_sample)
}

house_reflection_mult_inplace_cpp <- function(Gamma, v_p, right = TRUE) {
    invisible(.Call(`_NPBayes_house_reflection_mult_inplace_cpp`, Gamma, v_p, right))
}

house_reflection_mult_cpp <- function(Gamma, v_p, right = TRUE) {
    .Call(`_NPBayes_house_reflection_mult_cpp`, Gamma, v_p, right)
}

rcpp_hello <- function() {
    .Call(`_NPBayes_rcpp_hello`)
}

